services:
  server:
    # image: public.ecr.aws/y2x6m4d2/project/portfolio:latest
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 4000:4000
    restart: always
